#!/bin/bash

##
## Run a single command in a container
##

docker exec "$(docker ps --filter 'status=running' --filter "name=$1" -q | head -n 1)" \
    /bin/sh -c "if [ -f /bin/bash ]; then /bin/bash -c '$2'; else /bin/sh -c '$2'; fi"
