#!/bin/bash

##
## "SSH" into a docker container using a partial container name.
##

docker exec -it "$(docker ps --filter 'status=running' --filter "name=$1" -q | head -n 1)" \
    /bin/sh -c 'if [ -f /bin/bash ]; then /bin/bash; else /bin/sh; fi'
